sudo: false
dist: trusty

language: node_js

node_js:
  - "5"
  - "6"
  - "6.0.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8

notifications:
  email: false
